# Generated by Django 5.1.3 on 2024-12-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_task_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='work_time',
        ),
    ]
