# Generated by Django 5.1.3 on 2025-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_task_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sla_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
